version: '2'
services:
  server:
    build:
      context: ./zenofcoder-web/server
      dockerfile: Dockerfile-web-server
    restart: always
    command: bash web-production.sh

  db:
    restart: always

  nginx:
    restart: always
