version: '2'
services:
  server:
    volumes:
      - ./zenofcoder-web/server/:/opt/zenofcoder/zenofcoder-web/server/
    command: bash web-development.sh
  
  client:
    restart: unless-stopped
    volumes:
      - ./zenofcoder-web/client/:/opt/zenofcoder/zenofcoder-web/client/
    command: npm start

  nginx:
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/

