version: '2'
services:
  web:
    build:
      context: ./zenofcoder-web
      dockerfile: Dockerfile-web
    restart: always
    command: bash web-production.sh

  db:
    restart: always

  nginx:
    restart: always
