version: '2'
services:
  web:
    volumes:
      - ./zenofcoder-web/:/opt/zenofcoder/zenofcoder-web/
    command: bash web-development.sh

  nginx:
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/

