# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 20:20
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Title of the article.')),
                ('text', models.TextField(help_text='Content of the article.')),
                ('short', models.TextField(help_text='Few first lines of the article.')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Time of creation')),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Time of publication, can be feature.')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('author', models.ForeignKey(help_text='Author of the article.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
