# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 15:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Title of the article.')),
                ('content', models.TextField(help_text='Content of the article.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Time of creation')),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Time of publication, can be feature.')),
                ('slug', models.SlugField(unique=True)),
                ('author', models.ForeignKey(help_text='Author of the article.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='articles.Tag'),
        ),
    ]
